# OpenAI Configuration
openai:
  embedding_model: "jina-embeddings-v4"
  model: "qwen3-30b-a3b-Instruct-2507"
  api_key: "llamacpp"
  base_url: "http://localhost:8080/v1"

# GLM Configuration
glm:
  model: "glm-4-plus"
  api_key: "***"
  base_url: "https://open.bigmodel.cn/api/paas/v4"
  embedding_model: "embedding-3"

# Deepseek Configuration
deepseek:
  model: "deepseek-chat"
  api_key: "***"
  base_url: "https://api.deepseek.com"

# Model Parameters
model_params:
  openai_embedding_dim: 2048
  glm_embedding_dim: 2048
  max_token_size: 8192

# HiRAG Configuration
hirag:
  working_dir: "logger_hirag_data"
  enable_llm_cache: false
  enable_hierachical_mode: true
  embedding_batch_num: 6
  embedding_func_max_async: 8
  enable_naive_rag: false
